version: "3"

#needs manual creation of volume:
# docker volume create --driver local \
#    --opt type=none \
#    --opt device=path/to/project/root \
#   --opt o=bind nexus-data

#after it needs ownership
# mkdir -p ./nexus-data
# sudo chown -R 200:200 ./nexus-data
volumes:
  nexus-data: 
    external: true
    
name: latest-node-18-gateway-dev
services:
#Nexus
  nexus:
    image: sonatype/nexus3
    expose:
      - "8081"
      - "8082"
      #- "8083"
    ports:
      # UI
      - "8081:8081"
      # repositories http
      - "8082:8082"
      #- "8083:8083"
      # repositories https
      #- "8182:8182"
      #- "8183:8183"
    environment:
      - VIRTUAL_PORT=8081
    volumes:
      - "../../../nexus-data:/nexus-data"